# Generated by Django 4.2.1 on 2024-02-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
