# Generated by Django 4.2.1 on 2024-02-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_artwork_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
