# Generated by Django 4.2.1 on 2024-03-09 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_alter_project_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_atist', to='gallery.artist'),
        ),
    ]
