# Generated by Django 4.2.1 on 2024-03-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_alter_project_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
